### ADD MEMBER TO PROJECT
### ======================
POST {{baseUrl}}/projects/8/members
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": 7,
  "role": "SITE_ENGINEER"
}


> {%
    if (response.status === 201) {
        client.global.set("projectId", response.body.id);
    }
%}

### GET PROJECT MEMBERS
### ======================
GET {{baseUrl}}/projects/{{projectId}}/members
Authorization: Bearer {{token}}



### REMOVE PROJECT MEMBER
### ======================
DELETE {{baseUrl}}/projects/{{projectId}}/members/{{userId}}
Authorization: Bearer {{token}}
