create table projects
(
    id             bigint generated by default as identity
        primary key,
    budget_planned numeric(15, 2) not null,
    client_name    varchar(255)   not null,
    created_at     timestamp(6),
    location       varchar(255)   not null,
    name           varchar(255)   not null,
    project_code   varchar(255)   not null
        constraint uk1batb7mq0elcfcs3d6maqo6sg
            unique,
    start_date     date           not null,
    status         varchar(255)   not null
        constraint projects_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PLANNED'::character varying, 'ACTIVE'::character varying, 'ON_HOLD'::character varying, 'COMPLETED'::character varying])::text[])),
    updated_at     timestamp(6)
);

alter table projects
    owner to vaibhav;

