create table project_members
(
    id              bigint generated by default as identity
        primary key,
    created_at      timestamp(6),
    role_on_project varchar(255)
        constraint project_members_role_on_project_check
            check ((role_on_project)::text = ANY
                   ((ARRAY ['PROJECT_MANAGER'::character varying, 'SITE_ENGINEER'::character varying, 'SUPERVISOR'::character varying, 'CONTRACTOR'::character varying])::text[])),
    project_id      bigint not null
        constraint fkdki1sp2homqsdcvqm9yrix31g
            references projects,
    user_id         bigint not null
        constraint fkgul2el0qjk5lsvig3wgajwm77
            references users,
    constraint ukaydweb1re2g5786xaugww4u0
        unique (project_id, user_id)
);

alter table project_members
    owner to vaibhav;

