create table tasks
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6),
    description text         not null,
    due_date    date,
    status      varchar(255)
        constraint tasks_status_check
            check ((status)::text = ANY
                   ((ARRAY ['NOT_STARTED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'BLOCKED'::character varying])::text[])),
    title       varchar(255) not null,
    updated_at  timestamp(6),
    assignee_id bigint
        constraint fkekr1dgiqktpyoip3qmp6lxsit
            references users,
    created_by  bigint       not null
        constraint fk9dgm9t7wn4w3gh57h63g712lo
            references users,
    project_id  bigint       not null
        constraint fksfhn82y57i3k9uxww1s007acc
            references projects,
    deleted     boolean      not null
);

alter table tasks
    owner to vaibhav;

