create table users
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    email      varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    name       varchar(255) not null,
    password   varchar(255) not null,
    phone      varchar(255) not null
);

alter table users
    owner to vaibhav;

